# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0039_auto_20190430_0825'),
        ('parlamentares', '0027_auto_20190506_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancada',
            name='legislatura',
        ),
        migrations.RemoveField(
            model_name='bancada',
            name='partido',
        ),
        migrations.DeleteModel(
            name='CargoBancada',
        ),
        migrations.DeleteModel(
            name='Bancada',
        ),
    ]
